### ISSUE TITLE
Unable to load Iris sample file

### ISSUE THREAD

**Issue by tv3141** [SciTools/iris-grib#128]
https://github.com/SciTools/iris/issues/3070

**Comment by rcomer** [comment]
Linked issue refers to [this example](https://scitools.org.uk/iris/docs/v2.0/examples/General/polar_stereo.html), which does look broken.  I pasted the code into an up-to-date environment (Iris 3.2) and got

![grib_polar_stereo](https://user-images.githubusercontent.com/10599679/184172965-09b70269-21e1-4b7f-9a42-480bf1500b80.png)

So whatever the issue was appears to be fixed.
