### ISSUE TITLE
Simplify eccodes dependence in setup.py install_requires 

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris-grib#142]
Currently eccodes is only available on PyPI for windows: https://pypi.org/project/eccodes/#files

#141 amends the "install_requires" section of setup.py so that it only checks for eccodes if testing on windows.  This means that users will not be able to install eccodes using pip; they will have to install using conda instead.

However, this is a TEMPORARY AMENDMENT ONLY and must be reversed when ECMWF release eccodes on PyPI for all platforms.

**Comment by bjlittle** [comment]
@corinnebosley Raise this with ECMWF Software Support, see https://jira.ecmwf.int/browse/SUP-2777

**Comment by bjlittle** [comment]
Awaiting response from the ECMWF...

**Comment by rune-bk** [comment]
It will also attempt to install eccodes on OS X since sys.platform returns "Darwin" and you check for win in sys.platform 👍

**Comment by lbdreyer** [comment]
My understanding of the status of this is as follows:
From [ECMWF's ecCodes installation documentation](https://confluence.ecmwf.int//display/ECC/ecCodes+installation), it is suggested that the user needs to first install eccodes, and then they can install eccodes-python from PyPI. 

* #154 updated the install_requires from `eccodes` -> `eccodes-python`
* #180 removes the 'win' check so it will try to install eccodes-python in all cases 

Once #180 is in, iris-grib is configured to depend on eccodes-python only.
At this point I think we can close this ticket as we have gone as far as we can/should. 
I think we should only specify a dependency on eccodes-python, rather than eccodes-python AND eccodes. The dependency on eccodes should be handled by eccodes-python
