### ISSUE TITLE
Votable features on GitHub

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#155]
Like Iris : 
https://github.com/SciTools/iris/labels/Votable%20Feature
see https://vote.biglybt.com/SciTools/iris/Votable Feature

**Comment by jamesp** [comment]
Did this take off with iris? If not, shall we close this issue?

**Comment by pp-mo** [comment]
This link does work : https://vote.biglybt.com/SciTools/iris/Feature:%20Voteable 
( It is included in the detail text for the "Feature: Voteable" label )

So, there some votable issues still labelled in Iris, but they all look a bit old so maybe no-one is using it

**Comment by rcomer** [comment]
I don't think the Iris version was ever advertised to the user community.  Certainly https://github.com/SciTools/iris/issues/3307 is still open because of that and other questions.

More fundamentally, what happens if an issue does get lots of votes?  Ideally we would prioritise the most popular ones for implementation, but do we have the resource to do that?

**Comment by pp-mo** [comment]
Now achieved in Iris [via a computed table drawn from github](https://github.com/SciTools/iris/pull/4617), on a [docs page](https://scitools-iris.readthedocs.io/en/latest/voted_issues.html#voted-issues-top)

That seems like a very workable approach

**Comment by pp-mo** [comment]
Dead since Iris no longer uses these.
Replaced with simply github issue votes -- visible in Peloton, if we wish it
