### ISSUE TITLE
Migrate testing from Travis to Cirrus

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#242]
As Iris has done + for same reasons.

**Comment by trexfeathers** [comment]
Please have a look at the set up of [SciTools-incubator/iris-ugrid](https://github.com/SciTools-incubator/iris-ugrid) for a good (IMO) example of using Cirrus and Nox with an Iris-dependent repo.

**Comment by jamesp** [comment]
I'll take a look at this, anyone have any objections if I try and use github actions instead of cirrus?

**Comment by trexfeathers** [comment]
>I'll take a look at this, anyone have any objections if I try and use github actions instead of cirrus?

Environment caching is an important part of why we recently switched to Cirrus+Nox - the ecosystem of Iris dependencies makes environment build the majority of CI run time. There has also been recent discussion of using Cirrus compute credits to further speed up CI run time.

If GH actions can achieve similar run times somehow then I imagine there's no problem, but that seems like a big IF to me 🙂

(In future I've also been considering Cirrus' ability to run on a dedicated cloud machine (e.g. AWS) to potentially enable consistent benchmark results to be run directly from GH rather than running on on-premise machines. Can't benchmark on using traditional cloud like GH actions since the machines are virtualised so provide inconsistent results).

**Comment by jamesp** [comment]
👍 I'll use Cirrus!

**Comment by jamesp** [comment]
Work begun on this in #247
